# Plot p_s
set(0, "defaultlinelinewidth", 1.5);
## ToDo: The following are in ~/.octaverc but don't seem to affect the title or xlabel, ylabel
##set(0, "defaulttextfontsize", 18);
##set(0, "defaulttextfontname", "Times New Roman")
##set(0, "defaultaxesfontsize", 18);

# Plot p_s

plot(beta(1,:), p_stats(1,:,1,1,1),  "--;p_{sa}: λ_a=^{1}/_{16};", "color", [0.6 0.6 0.6], ...
     beta(1,:), p_stats(2,:,1,1,1),  "--;p_{sa}: λ_a=^{2}/_{16};", "color", [0.6 0.6 0.6], ...
     beta(1,:), p_stats(3,:,1,1,1),   "-;p_{sa}: λ_a=^{3}/_{16};", "color", [0.6 0.6 0.6], ...
     beta(1,:), p_stats(4,:,1,1,1),   ":;p_{sa}: λ_a=^{4}/_{16};", "color", "magenta", "linewidth", 2.5, ...
     beta(1,:), p_stats(5,:,1,1,1),  "--;p_{sa}: λ_a=^{5}/_{16};", "color", "magenta", ...
     beta(1,:), p_stats(6,:,1,1,1),   "-;p_{sa}: λ_a=^{6}/_{16};", "color", "magenta", ...
     beta(1,:), p_stats(7,:,1,1,1),   ":;p_{sa}: λ_a=^{7}/_{16};", "color", "blue", "linewidth", 2.5, ...
     beta(1,:), p_stats(8,:,1,1,1),  "--;p_{sa}: λ_a=^{8}/_{16};", "color", "blue", ...
     beta(1,:), p_stats(9,:,1,1,1),   "-;p_{sa}: λ_a=^{9}/_{16};", "color", "blue", ...
     beta(1,:), p_stats(10,:,1,1,1),   ":;p_{sa}: λ_a=^{10}/_{16};", "color", [0.6 0 0.6], "linewidth", 2.5,  ...
     beta(1,:), p_stats(11,:,1,1,1), "--;p_{sa}: λ_a=^{11}/_{16};", "color", [0.6 0 0.6],  ...
     beta(1,:), p_stats(12,:,1,1,1),  "-;p_{sa}: λ_a=^{12}/_{16};", "color", [0.6 0 0.6], ...
     beta(1,:), p_stats(13,:,1,1,1),  ":;p_{sa}: λ_a=^{13}/_{16};", "color", "black", "linewidth", 2.5, ...
     beta(1,:), p_stats(14,:,1,1,1), "--;p_{sa}: λ_a=^{14}/_{16};", "color", "black", ...
     beta(1,:), p_stats(15,:,1,1,1),  "-;p_{sa}: λ_a=^{15}/_{16};", "color", "black")
axis([0 double(betaSum)/betas*1.2 0 1.04]);
h_tit = title(["Sojourn marking of two unresponsive flows, a & b\n" ...
       "Capacity fractions, λ_a & λ_b;   Utilization, Σλ = " ...
       num2str(double(lambdaSum)/lambdas*100) "%;   " ...
       "Burst sizes β_a & β_b, where Σβ = " num2str(double(betaSum)/betas*100) ...
       "% of marking threshold"]);
h_xl = xlabel(["Normalized burst size of flow a,  β_a"]);
h_yl = ylabel("Sojourn-based marking probability of flow a, p_{sa}\n\n");
h_leg = legend();
set(h_tit, 'fontname', 'Times New Roman', 'fontsize', 20)
set(h_xl, 'fontname', 'Times New Roman', 'fontsize', 20)
set(h_yl, 'fontname', 'Times New Roman', 'fontsize', 20)
set(h_leg, 'fontname', 'Times New Roman', 'fontsize', 14)
savefile = [savepre, "_p_s_", savemid, savesuf];
print([savefile ".pdf"]);

# Plot p_e
figure(2)
plot(beta(1,:), p_stats(1,:,1,2,1),   ":;p_{ea}: λ_a=^{1}/_{16};", "color", [0.6 0.6 0.6], "linewidth", 2.5, ...
     beta(1,:), p_stats(2,:,1,2,1),  "--;p_{ea}: λ_a=^{2}/_{16};", "color", [0.6 0.6 0.6], ...
     beta(1,:), p_stats(3,:,1,2,1),   "-;p_{ea}: λ_a=^{3}/_{16};", "color", [0.6 0.6 0.6], ...
     beta(1,:), p_stats(4,:,1,2,1),   ":;p_{ea}: λ_a=^{4}/_{16};", "color", "magenta", "linewidth", 2.5, ...
     beta(1,:), p_stats(5,:,1,2,1),  "--;p_{ea}: λ_a=^{5}/_{16};", "color", "magenta", ...
     beta(1,:), p_stats(6,:,1,2,1),   "-;p_{ea}: λ_a=^{6}/_{16};", "color", "magenta", ...
     beta(1,:), p_stats(7,:,1,2,1),   ":;p_{ea}: λ_a=^{7}/_{16};", "color", "blue", "linewidth", 2.5, ...
     beta(1,:), p_stats(8,:,1,2,1),  "--;p_{ea}: λ_a=^{8}/_{16};", "color", "blue", ...
     beta(1,:), p_stats(9,:,1,2,1),   "-;p_{ea}: λ_a=^{9}/_{16};", "color", "blue", ...
     beta(1,:), p_stats(10,:,1,2,1),  ":;p_{ea}: λ_a=^{10}/_{16};", "color", [0.6 0 0.6], "linewidth", 2.5,  ...
     beta(1,:), p_stats(11,:,1,2,1), "--;p_{ea}: λ_a=^{11}/_{16};", "color", [0.6 0 0.6],  ...
     beta(1,:), p_stats(12,:,1,2,1),  "-;p_{ea}: λ_a=^{12}/_{16};", "color", [0.6 0 0.6], ...
     beta(1,:), p_stats(13,:,1,2,1),  ":;p_{ea}: λ_a=^{13}/_{16};", "color", "black", "linewidth", 2.5, ...
     beta(1,:), p_stats(14,:,1,2,1), "--;p_{ea}: λ_a=^{14}/_{16};", "color", "black", ...
     beta(1,:), p_stats(15,:,1,2,1),  "-;p_{ea}: λ_a=^{15}/_{16};", "color", "black")
axis([0 double(betaSum)/betas*1.2 0 1.04]);
h_tit = title(["Expected Service Time (EST) marking of two unresponsive flows, a & b\n" ...
       "Capacity fractions, λ_a & λ_b;   Utilization, Σλ = " ...
       num2str(double(lambdaSum)/lambdas*100) "%;   " ...
       "Burst sizes β_a & β_b, where Σβ = " num2str(double(betaSum)/betas*100) ...
       "% of marking threshold"]);
h_xl = xlabel(["Normalized burst size of flow a,  β_a"]);
h_yl = ylabel("EST-based marking probability of flow a,  p_{ea}\n\n");
h_leg = legend();
set(h_tit, 'fontname', 'Times New Roman', 'fontsize', 20);
set(h_xl, 'fontname', 'Times New Roman', 'fontsize', 20);
set(h_yl, 'fontname', 'Times New Roman', 'fontsize', 20);
set(h_leg, 'fontname', 'Times New Roman', 'fontsize', 14);
savefile = [savepre, "_p_e_", savemid, savesuf];
print([savefile ".pdf"]);
